name: timezones
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^0.6.0
  instant: ^0.4.1
  intl: ^0.17.0
  location_api:
    path: packages/location_api
  persistent_storage:
    path: packages/storage/persistent_storage
  shared_preferences: ^2.0.6
  time_zone_api:
    path: packages/time_zone_api
  time_zone_repository:
    path: packages/time_zone_repository
  time_zones_ui:
    path: packages/time_zones_ui

dev_dependencies:
  bloc_test: ^8.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

dependency_overrides:
  bloc:
    git:
      url: https://github.com/felangel/bloc
      path: packages/bloc
      ref: 568c92b80342b8a00b4d926d38ffb7a041893a10
  bloc_test:
    git:
      url: https://github.com/felangel/bloc
      path: packages/bloc_test
      ref: 568c92b80342b8a00b4d926d38ffb7a041893a10
  flutter_bloc:
    git:
      url: https://github.com/felangel/bloc
      path: packages/flutter_bloc
      ref: 568c92b80342b8a00b4d926d38ffb7a041893a10

flutter:
  uses-material-design: true
  generate: true
