name: timezones
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  location_api:
    path: packages/location_api
  time_zone_api:
    path: packages/time_zone_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
