name: time_zone_repository
description: Repository for time zone
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  location_api:
    path: ../location_api
  time_zone_api:
    path: ../time_zone_api

dev_dependencies:
  mocktail: ^0.1.4
  test: ^1.16.4
  very_good_analysis: ^2.3.0
