name: time_zone_api
description: Time Zone API
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^4.0.0
  mocktail: ^0.1.0
  test: ^1.16.4
  very_good_analysis: ^2.1.1
